"""Add price_type to product

Revision ID: 308cb133e377
Revises: 675ae8d5cca2
Create Date: 2025-12-19 09:56:23.644361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308cb133e377'
down_revision = '675ae8d5cca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_type', sa.String(length=20), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('price_type')

    # ### end Alembic commands ###
