"""empty message

Revision ID: 560711fda07f
Revises: 1e0554c857ce
Create Date: 2025-12-06 17:36:35.808830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560711fda07f'
down_revision = '1e0554c857ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('delivery')
        batch_op.drop_column('city')
        batch_op.drop_column('region')
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
