"""Add confirmed_at to User

Revision ID: 675ae8d5cca2
Revises: a435d8a329e5
Create Date: 2025-12-15 21:38:21.680980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675ae8d5cca2'
down_revision = 'a435d8a329e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')

    # ### end Alembic commands ###
