"""Add vat_included to Product

Revision ID: 925c369c1a95
Revises: 2b7792ea034f
Create Date: 2025-12-04 19:50:28.580365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925c369c1a95'
down_revision = '2b7792ea034f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_included', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('vat_included')

    # ### end Alembic commands ###
